name: Defender CLI Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: write
  id-token: write

jobs:
  defender-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Download Defender CLI
      run: |
       curl -L -o defender "https://cli.dfd.security.azure.com/public/v2/latest/Defender_linux-x64" && chmod +x defender

    - name: Run Defender CLI Scan (Built)
      run: |
        ./defender scan fs . --include ai-vuln --output defender.sarif
      continue-on-error: true
      env:
        DEFENDER_ASPM_TENANT_ID: ${{ secrets.DEFENDER_ASPM_TENANT_ID }}
        DEFENDER_ASPM_CLIENT_ID: ${{ secrets.DEFENDER_ASPM_TENANT_ID }}
        DEFENDER_ASPM_CLIENT_SECRET: ${{ secrets.DEFENDER_ASPM_TENANT_ID }}

    - name: Upload production-ready artifact
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: output.html

    - name: Upload SARIF to Code Scanning
      if: always()
      uses: github/codeql-action/upload-sarif@v4
      continue-on-error: true
      with:
        sarif_file: defender.sarif

        
